<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["agencia/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["agencia/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>CodAgencia</th>
            <th>Descripcion</th>
            <th>EstadoRegistro</th>
            <th>UsuarioInsercion</th>
            <th>FechaInsercion</th>
            <th>UsuarioModificacion</th>
            <th>FechaModificacion</th>
            <th>CodEmpresa</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $agencia): ?>
            <tr>
                <td><?php echo $agencia->codAgencia ?></td>
            <td><?php echo $agencia->descripcion ?></td>
            <td><?php echo $agencia->estadoRegistro ?></td>
            <td><?php echo $agencia->usuarioInsercion ?></td>
            <td><?php echo $agencia->fechaInsercion ?></td>
            <td><?php echo $agencia->usuarioModificacion ?></td>
            <td><?php echo $agencia->fechaModificacion ?></td>
            <td><?php echo $agencia->codEmpresa ?></td>

                <td><?php echo $this->tag->linkTo(["agencia/edit/" . $agencia->codAgencia, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["agencia/delete/" . $agencia->codAgencia, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("agencia/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("agencia/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("agencia/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("agencia/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
