<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["usuario/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["usuario/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>CodUsuario</th>
            <th>NombreUsuario</th>
            <th>PasswordUsuario</th>
            <th>CantidadIntentos</th>
            <th>IndicadorUsuarioAdministrador</th>
            <th>EstadoRegistro</th>
            <th>UsuarioInsercion</th>
            <th>FechaInsercion</th>
            <th>UsuarioModificacion</th>
            <th>FechaModificacion</th>
            <th>CodPersona</th>
            <th>CodEmpresa</th>
            <th>CodAgencia</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $usuario): ?>
            <tr>
                <td><?php echo $usuario->codUsuario ?></td>
            <td><?php echo $usuario->nombreUsuario ?></td>
            <td><?php echo $usuario->passwordUsuario ?></td>
            <td><?php echo $usuario->cantidadIntentos ?></td>
            <td><?php echo $usuario->indicadorUsuarioAdministrador ?></td>
            <td><?php echo $usuario->estadoRegistro ?></td>
            <td><?php echo $usuario->usuarioInsercion ?></td>
            <td><?php echo $usuario->fechaInsercion ?></td>
            <td><?php echo $usuario->usuarioModificacion ?></td>
            <td><?php echo $usuario->fechaModificacion ?></td>
            <td><?php echo $usuario->codPersona ?></td>
            <td><?php echo $usuario->codEmpresa ?></td>
            <td><?php echo $usuario->codAgencia ?></td>

                <td><?php echo $this->tag->linkTo(["usuario/edit/" . $usuario->codUsuario, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["usuario/delete/" . $usuario->codUsuario, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("usuario/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("usuario/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("usuario/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("usuario/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
