<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search persona
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["persona/new", "Create persona"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "persona/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCodpersona" class="col-sm-2 control-label">CodPersona</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codPersona", "type" => "number", "class" => "form-control", "id" => "fieldCodpersona"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNombrepersona" class="col-sm-2 control-label">NombrePersona</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombrePersona", "size" => 30, "class" => "form-control", "id" => "fieldNombrepersona"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldApepat" class="col-sm-2 control-label">ApePat</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["apePat", "size" => 30, "class" => "form-control", "id" => "fieldApepat"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldApemat" class="col-sm-2 control-label">ApeMat</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["apeMat", "size" => 30, "class" => "form-control", "id" => "fieldApemat"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSexo" class="col-sm-2 control-label">Sexo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["sexo", "size" => 30, "class" => "form-control", "id" => "fieldSexo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEdad" class="col-sm-2 control-label">Edad</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["edad", "type" => "number", "class" => "form-control", "id" => "fieldEdad"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNumerodocumento" class="col-sm-2 control-label">NumeroDocumento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["numeroDocumento", "size" => 30, "class" => "form-control", "id" => "fieldNumerodocumento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRazonsocial" class="col-sm-2 control-label">RazonSocial</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["razonSocial", "size" => 30, "class" => "form-control", "id" => "fieldRazonsocial"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEstadoregistro" class="col-sm-2 control-label">EstadoRegistro</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["estadoRegistro", "size" => 30, "class" => "form-control", "id" => "fieldEstadoregistro"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUsuarioinsercion" class="col-sm-2 control-label">UsuarioInsercion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["usuarioInsercion", "size" => 30, "class" => "form-control", "id" => "fieldUsuarioinsercion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechainsercion" class="col-sm-2 control-label">FechaInsercion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaInsercion", "size" => 30, "class" => "form-control", "id" => "fieldFechainsercion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUsuariomodificacion" class="col-sm-2 control-label">UsuarioModificacion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["usuarioModificacion", "size" => 30, "class" => "form-control", "id" => "fieldUsuariomodificacion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechamodificacion" class="col-sm-2 control-label">FechaModificacion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaModificacion", "size" => 30, "class" => "form-control", "id" => "fieldFechamodificacion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodtipodocumento" class="col-sm-2 control-label">CodTipoDocumento</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codTipoDocumento", "type" => "number", "class" => "form-control", "id" => "fieldCodtipodocumento"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTipopersona" class="col-sm-2 control-label">TipoPersona</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tipoPersona", "size" => 30, "class" => "form-control", "id" => "fieldTipopersona"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodempresa" class="col-sm-2 control-label">CodEmpresa</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codEmpresa", "type" => "number", "class" => "form-control", "id" => "fieldCodempresa"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
