<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["persona/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["persona/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>CodPersona</th>
            <th>NombrePersona</th>
            <th>ApePat</th>
            <th>ApeMat</th>
            <th>Sexo</th>
            <th>Edad</th>
            <th>NumeroDocumento</th>
            <th>RazonSocial</th>
            <th>EstadoRegistro</th>
            <th>UsuarioInsercion</th>
            <th>FechaInsercion</th>
            <th>UsuarioModificacion</th>
            <th>FechaModificacion</th>
            <th>CodTipoDocumento</th>
            <th>TipoPersona</th>
            <th>CodEmpresa</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $persona): ?>
            <tr>
                <td><?php echo $persona->codPersona ?></td>
            <td><?php echo $persona->nombrePersona ?></td>
            <td><?php echo $persona->apePat ?></td>
            <td><?php echo $persona->apeMat ?></td>
            <td><?php echo $persona->sexo ?></td>
            <td><?php echo $persona->edad ?></td>
            <td><?php echo $persona->numeroDocumento ?></td>
            <td><?php echo $persona->razonSocial ?></td>
            <td><?php echo $persona->estadoRegistro ?></td>
            <td><?php echo $persona->usuarioInsercion ?></td>
            <td><?php echo $persona->fechaInsercion ?></td>
            <td><?php echo $persona->usuarioModificacion ?></td>
            <td><?php echo $persona->fechaModificacion ?></td>
            <td><?php echo $persona->codTipoDocumento ?></td>
            <td><?php echo $persona->tipoPersona ?></td>
            <td><?php echo $persona->codEmpresa ?></td>

                <td><?php echo $this->tag->linkTo(["persona/edit/" . $persona->codPersona, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["persona/delete/" . $persona->codPersona, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("persona/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("persona/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("persona/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("persona/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
