<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["empresa", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit empresa
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "empresa/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldNombreempresa" class="col-sm-2 control-label">NombreEmpresa</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nombreEmpresa", "size" => 30, "class" => "form-control", "id" => "fieldNombreempresa"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRazonsocial" class="col-sm-2 control-label">RazonSocial</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["razonSocial", "size" => 30, "class" => "form-control", "id" => "fieldRazonsocial"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLimiteusuarios" class="col-sm-2 control-label">LimiteUsuarios</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["limiteUsuarios", "type" => "number", "class" => "form-control", "id" => "fieldLimiteusuarios"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdentificadorempresa" class="col-sm-2 control-label">IdentificadorEmpresa</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["identificadorEmpresa", "size" => 30, "class" => "form-control", "id" => "fieldIdentificadorempresa"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEstadoregistro" class="col-sm-2 control-label">EstadoRegistro</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["estadoRegistro", "size" => 30, "class" => "form-control", "id" => "fieldEstadoregistro"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUsuarioinsercion" class="col-sm-2 control-label">UsuarioInsercion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["usuarioInsercion", "size" => 30, "class" => "form-control", "id" => "fieldUsuarioinsercion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechainsercion" class="col-sm-2 control-label">FechaInsercion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaInsercion", "size" => 30, "class" => "form-control", "id" => "fieldFechainsercion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUsuariomodificacion" class="col-sm-2 control-label">UsuarioModificacion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["usuarioModificacion", "size" => 30, "class" => "form-control", "id" => "fieldUsuariomodificacion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechamodificacion" class="col-sm-2 control-label">FechaModificacion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaModificacion", "size" => 30, "class" => "form-control", "id" => "fieldFechamodificacion"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
