<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["empresa/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["empresa/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>CodEmpresa</th>
            <th>NombreEmpresa</th>
            <th>RazonSocial</th>
            <th>LimiteUsuarios</th>
            <th>IdentificadorEmpresa</th>
            <th>EstadoRegistro</th>
            <th>UsuarioInsercion</th>
            <th>FechaInsercion</th>
            <th>UsuarioModificacion</th>
            <th>FechaModificacion</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $empresa): ?>
            <tr>
                <td><?php echo $empresa->codEmpresa ?></td>
            <td><?php echo $empresa->nombreEmpresa ?></td>
            <td><?php echo $empresa->razonSocial ?></td>
            <td><?php echo $empresa->limiteUsuarios ?></td>
            <td><?php echo $empresa->identificadorEmpresa ?></td>
            <td><?php echo $empresa->estadoRegistro ?></td>
            <td><?php echo $empresa->usuarioInsercion ?></td>
            <td><?php echo $empresa->fechaInsercion ?></td>
            <td><?php echo $empresa->usuarioModificacion ?></td>
            <td><?php echo $empresa->fechaModificacion ?></td>

                <td><?php echo $this->tag->linkTo(["empresa/edit/" . $empresa->codEmpresa, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["empresa/delete/" . $empresa->codEmpresa, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("empresa/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("empresa/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("empresa/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("empresa/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
