<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["tipo_documento/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["tipo_documento/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>CodTipoDocumento</th>
            <th>Descripcion</th>
            <th>EstadoRegistro</th>
            <th>UsuarioInsercion</th>
            <th>FechaInsercion</th>
            <th>UsuarioModificacion</th>
            <th>FechaModificacion</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $tipo_documento): ?>
            <tr>
                <td><?php echo $tipo_documento->codTipoDocumento ?></td>
            <td><?php echo $tipo_documento->descripcion ?></td>
            <td><?php echo $tipo_documento->estadoRegistro ?></td>
            <td><?php echo $tipo_documento->usuarioInsercion ?></td>
            <td><?php echo $tipo_documento->fechaInsercion ?></td>
            <td><?php echo $tipo_documento->usuarioModificacion ?></td>
            <td><?php echo $tipo_documento->fechaModificacion ?></td>

                <td><?php echo $this->tag->linkTo(["tipo_documento/edit/" . $tipo_documento->codTipoDocumento, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["tipo_documento/delete/" . $tipo_documento->codTipoDocumento, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("tipo_documento/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("tipo_documento/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("tipo_documento/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("tipo_documento/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
