<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search tipo_empleado
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["tipo_empleado/new", "Create tipo_empleado"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "tipo_empleado/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCodtipoempleado" class="col-sm-2 control-label">CodTipoEmpleado</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codTipoEmpleado", "type" => "number", "class" => "form-control", "id" => "fieldCodtipoempleado"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescripcion" class="col-sm-2 control-label">Descripcion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["descripcion", "size" => 30, "class" => "form-control", "id" => "fieldDescripcion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEstadoregistro" class="col-sm-2 control-label">EstadoRegistro</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["estadoRegistro", "size" => 30, "class" => "form-control", "id" => "fieldEstadoregistro"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUsuarioinsercion" class="col-sm-2 control-label">UsuarioInsercion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["usuarioInsercion", "size" => 30, "class" => "form-control", "id" => "fieldUsuarioinsercion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechainsercion" class="col-sm-2 control-label">FechaInsercion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaInsercion", "size" => 30, "class" => "form-control", "id" => "fieldFechainsercion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUsuariomodificacion" class="col-sm-2 control-label">UsuarioModificacion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["usuarioModificacion", "size" => 30, "class" => "form-control", "id" => "fieldUsuariomodificacion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFechamodificacion" class="col-sm-2 control-label">FechaModificacion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fechaModificacion", "size" => 30, "class" => "form-control", "id" => "fieldFechamodificacion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodempresa" class="col-sm-2 control-label">CodEmpresa</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codEmpresa", "type" => "number", "class" => "form-control", "id" => "fieldCodempresa"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
