<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["empleado", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit empleado
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "empleado/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCodpersona" class="col-sm-2 control-label">CodPersona</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codPersona", "type" => "number", "class" => "form-control", "id" => "fieldCodpersona"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodtipoempleado" class="col-sm-2 control-label">CodTipoEmpleado</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codTipoEmpleado", "type" => "number", "class" => "form-control", "id" => "fieldCodtipoempleado"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodempresa" class="col-sm-2 control-label">CodEmpresa</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codEmpresa", "type" => "number", "class" => "form-control", "id" => "fieldCodempresa"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodagencia" class="col-sm-2 control-label">CodAgencia</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codAgencia", "type" => "number", "class" => "form-control", "id" => "fieldCodagencia"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
